language: c
compiler: gcc
os: linux
dist: trusty

services:
  - docker

_shared: &shared
  before_install: docker pull $IMAGE
  script:
    - source $TRAVIS_BUILD_DIR/.travis-vars
    - docker run -u root -v $PWD/gphoto2-updater.sh:/usr/local/bin/gphoto2-updater.sh $IMAGE /bin/bash -c "set -ux; $INSTALL_CMD && $GPHOTO2_TEST_CMD && $LIBGPHOTO2_TEST_CMD"

jobs:
  include:
      - name: Ubuntu 20.04
        env:
          - IMAGE="ubuntu:18.04"
        <<: *shared   
      - name: Ubuntu 18.04
        env:
          - IMAGE="ubuntu:18.04"
        <<: *shared 
      - name: Ubuntu 16.04
        env:
          - IMAGE="ubuntu:16.04"
        <<: *shared 
      - name: Debian 8
        env:
          - IMAGE="debian:8"
        <<: *shared 
      - name: Debian 9
        env:
          - IMAGE="debian:9"
        <<: *shared 
      - name: Debian 9
        env:
          - IMAGE="debian:10"
        <<: *shared 
